version: 2
sources:
  - name: public
    schema: public
    tables:
     - name: lobeliacosmetics

models:
  - name: lobeliapha_transformed
    decription: "Pharmacy Data Transformed"
    columns:
      - name: ID
        description: "Unique Id for each message"
        data_test:
          - unique
          - not_null
      - name: date
        description: "Date of the message"
        data_test:
          - date
        

